server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ant_move?serverTimezone=GMT
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml
