server:
  port: 8081
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ant_move?serverTimezone=GMT
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置email
  mail:
    default-encoding: UTF-8
    username: 1559331512@qq.com
    password: ffigyhmutqfhgehc
    host: smtp.qq.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
